#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/sdo/ce/examples/codecs/videnc_copy
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/include/utils.tci
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/codec_engine_3_22_01_06/codec_engine.bld:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/codec_engine_3_22_01_06/codec_engine.bld
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/ITarget.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/ITarget.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Linux86.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Linux86.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Mingw.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/Mingw.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/MVArm9.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/MVArm9.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/UCArm9.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/UCArm9.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/package.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/package.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv6.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/GCArmv7A.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M3.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M3.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4F.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/M4F.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/MVArm9.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/MVArm9.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/UCArm9.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/UCArm9.xs
/home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/package.xs:
package.mak: /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/package.xs
package.mak: package.bld
endif

ti.targets.elf.C674.rootDir ?= /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/dsp-devkit/cgt6x_7_3_1/
ti.targets.elf.packageBase ?= /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/
gnu.targets.arm.GCArmv5T.rootDir ?= /home/ruiva/project/CodeSourcery/Sourcery_G++_Lite/
gnu.targets.arm.packageBase ?= /home/ruiva/project/ruiva-dm8148-dvsdk5/ti-ezsdk_dm814x-evm_5_05_01_04/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674

.PRECIOUS: $(XDCCFGDIR)/%.ov5T
.PHONY: all,v5T .dlls,v5T .executables,v5T test,v5T
all,v5T: .executables,v5T
.executables,v5T: .libraries,v5T
.executables,v5T: .dlls,v5T
.dlls,v5T: .libraries,v5T
.libraries,v5T: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,v5T
	@$(ECHO) xdc .executables,v5T
	@$(ECHO) xdc .libraries,v5T
	@$(ECHO) xdc .dlls,v5T


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.ce.examples.codecs.videnc_copy.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ce.examples.codecs.videnc_copy" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.ce.examples.codecs.videnc_copy $@

.libraries,e674 .libraries: lib/videnc_copy_dma.ae674

-include lib/videnc_copy_dma.ae674.mak
lib/videnc_copy_dma.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/videnc_copy_dma/package/package_ti.sdo.ce.examples.codecs.videnc_copy.oe674 package/lib/lib/videnc_copy_dma/videnc_copy.oe674 package/lib/lib/videnc_copy_dma/VAD.oe674 package/lib/lib/videnc_copy_dma/Filter.oe674 package/lib/lib/videnc_copy_dma/CalcGaussLh.oe674 package/lib/lib/videnc_copy_dma/DSPCFFT.oe674 package/lib/lib/videnc_copy_dma/DspWordDict.oe674 package/lib/lib/videnc_copy_dma/DSPCmdWordRecg.oe674 package/lib/lib/videnc_copy_dma/DspCodeBooks.oe674 package/lib/lib/videnc_copy_dma/DspGMMCalc.oe674 package/lib/lib/videnc_copy_dma/DSPMFCC.oe674 package/lib/lib/videnc_copy_dma/DSPSegmentAlgorithm.oe674 package/lib/lib/videnc_copy_dma/DSPStateTrace.oe674 package/lib/lib/videnc_copy_dma/DSPStateTraceBin.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/videnc_copy_dma/package/package_ti.sdo.ce.examples.codecs.videnc_copy.oe674 package/lib/lib/videnc_copy_dma/videnc_copy.oe674 package/lib/lib/videnc_copy_dma/VAD.oe674 package/lib/lib/videnc_copy_dma/Filter.oe674 package/lib/lib/videnc_copy_dma/CalcGaussLh.oe674 package/lib/lib/videnc_copy_dma/DSPCFFT.oe674 package/lib/lib/videnc_copy_dma/DspWordDict.oe674 package/lib/lib/videnc_copy_dma/DSPCmdWordRecg.oe674 package/lib/lib/videnc_copy_dma/DspCodeBooks.oe674 package/lib/lib/videnc_copy_dma/DspGMMCalc.oe674 package/lib/lib/videnc_copy_dma/DSPMFCC.oe674 package/lib/lib/videnc_copy_dma/DSPSegmentAlgorithm.oe674 package/lib/lib/videnc_copy_dma/DSPStateTrace.oe674 package/lib/lib/videnc_copy_dma/DSPStateTraceBin.oe674 
lib/videnc_copy_dma.ae674: export C_DIR=
lib/videnc_copy_dma.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/videnc_copy_dma.ae674
.libraries,e674 .libraries: lib/videnc_copy.ae674

-include lib/videnc_copy.ae674.mak
lib/videnc_copy.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.oe674 package/lib/lib/videnc_copy/videnc_copy.oe674 package/lib/lib/videnc_copy/VAD.oe674 package/lib/lib/videnc_copy/Filter.oe674 package/lib/lib/videnc_copy/CalcGaussLh.oe674 package/lib/lib/videnc_copy/DSPCFFT.oe674 package/lib/lib/videnc_copy/DspWordDict.oe674 package/lib/lib/videnc_copy/DSPCmdWordRecg.oe674 package/lib/lib/videnc_copy/DspCodeBooks.oe674 package/lib/lib/videnc_copy/DspGMMCalc.oe674 package/lib/lib/videnc_copy/DSPMFCC.oe674 package/lib/lib/videnc_copy/DSPSegmentAlgorithm.oe674 package/lib/lib/videnc_copy/DSPStateTrace.oe674 package/lib/lib/videnc_copy/DSPStateTraceBin.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.oe674 package/lib/lib/videnc_copy/videnc_copy.oe674 package/lib/lib/videnc_copy/VAD.oe674 package/lib/lib/videnc_copy/Filter.oe674 package/lib/lib/videnc_copy/CalcGaussLh.oe674 package/lib/lib/videnc_copy/DSPCFFT.oe674 package/lib/lib/videnc_copy/DspWordDict.oe674 package/lib/lib/videnc_copy/DSPCmdWordRecg.oe674 package/lib/lib/videnc_copy/DspCodeBooks.oe674 package/lib/lib/videnc_copy/DspGMMCalc.oe674 package/lib/lib/videnc_copy/DSPMFCC.oe674 package/lib/lib/videnc_copy/DSPSegmentAlgorithm.oe674 package/lib/lib/videnc_copy/DSPStateTrace.oe674 package/lib/lib/videnc_copy/DSPStateTraceBin.oe674 
lib/videnc_copy.ae674: export C_DIR=
lib/videnc_copy.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/videnc_copy.ae674
.libraries,v5T .libraries: lib/videnc_copy.av5T

-include lib/videnc_copy.av5T.mak
lib/videnc_copy.av5T: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.ov5T package/lib/lib/videnc_copy/videnc_copy.ov5T package/lib/lib/videnc_copy/VAD.ov5T package/lib/lib/videnc_copy/Filter.ov5T package/lib/lib/videnc_copy/CalcGaussLh.ov5T package/lib/lib/videnc_copy/DSPCFFT.ov5T package/lib/lib/videnc_copy/DspWordDict.ov5T package/lib/lib/videnc_copy/DSPCmdWordRecg.ov5T package/lib/lib/videnc_copy/DspCodeBooks.ov5T package/lib/lib/videnc_copy/DspGMMCalc.ov5T package/lib/lib/videnc_copy/DSPMFCC.ov5T package/lib/lib/videnc_copy/DSPSegmentAlgorithm.ov5T package/lib/lib/videnc_copy/DSPStateTrace.ov5T package/lib/lib/videnc_copy/DSPStateTraceBin.ov5T  into $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/bin/ar  cr $@   package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.ov5T package/lib/lib/videnc_copy/videnc_copy.ov5T package/lib/lib/videnc_copy/VAD.ov5T package/lib/lib/videnc_copy/Filter.ov5T package/lib/lib/videnc_copy/CalcGaussLh.ov5T package/lib/lib/videnc_copy/DSPCFFT.ov5T package/lib/lib/videnc_copy/DspWordDict.ov5T package/lib/lib/videnc_copy/DSPCmdWordRecg.ov5T package/lib/lib/videnc_copy/DspCodeBooks.ov5T package/lib/lib/videnc_copy/DspGMMCalc.ov5T package/lib/lib/videnc_copy/DSPMFCC.ov5T package/lib/lib/videnc_copy/DSPSegmentAlgorithm.ov5T package/lib/lib/videnc_copy/DSPStateTrace.ov5T package/lib/lib/videnc_copy/DSPStateTraceBin.ov5T 
lib/videnc_copy.av5T: export LD_LIBRARY_PATH=

clean,v5T clean::
	-$(RM) lib/videnc_copy.av5T
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.sdo.ce.examples.codecs.videnc_copy.oe674,copy
package_ti.sdo.ce.examples.codecs.videnc_copy.oe674,copy : package_ti.sdo.ce.examples.codecs.videnc_copy.oe674,0,copy package_ti.sdo.ce.examples.codecs.videnc_copy.oe674,1,copy 
	@

package_ti.sdo.ce.examples.codecs.videnc_copy.oe674,0,copy : package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.oe674
package_ti.sdo.ce.examples.codecs.videnc_copy.oe674,1,copy : package/lib/lib/videnc_copy_dma/package/package_ti.sdo.ce.examples.codecs.videnc_copy.oe674
.PHONY: package_ti.sdo.ce.examples.codecs.videnc_copy.se674,copy
package_ti.sdo.ce.examples.codecs.videnc_copy.se674,copy : package_ti.sdo.ce.examples.codecs.videnc_copy.se674,0,copy package_ti.sdo.ce.examples.codecs.videnc_copy.se674,1,copy 
	@

package_ti.sdo.ce.examples.codecs.videnc_copy.se674,0,copy : package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.se674
package_ti.sdo.ce.examples.codecs.videnc_copy.se674,1,copy : package/lib/lib/videnc_copy_dma/package/package_ti.sdo.ce.examples.codecs.videnc_copy.se674
.PHONY: videnc_copy.oe674,copy
videnc_copy.oe674,copy : videnc_copy.oe674,0,copy videnc_copy.oe674,1,copy 
	@

videnc_copy.oe674,0,copy : package/lib/lib/videnc_copy/videnc_copy.oe674
videnc_copy.oe674,1,copy : package/lib/lib/videnc_copy_dma/videnc_copy.oe674
.PHONY: videnc_copy.se674,copy
videnc_copy.se674,copy : videnc_copy.se674,0,copy videnc_copy.se674,1,copy 
	@

videnc_copy.se674,0,copy : package/lib/lib/videnc_copy/videnc_copy.se674
videnc_copy.se674,1,copy : package/lib/lib/videnc_copy_dma/videnc_copy.se674
.PHONY: VAD.oe674,copy
VAD.oe674,copy : VAD.oe674,0,copy VAD.oe674,1,copy 
	@

VAD.oe674,0,copy : package/lib/lib/videnc_copy/VAD.oe674
VAD.oe674,1,copy : package/lib/lib/videnc_copy_dma/VAD.oe674
.PHONY: VAD.se674,copy
VAD.se674,copy : VAD.se674,0,copy VAD.se674,1,copy 
	@

VAD.se674,0,copy : package/lib/lib/videnc_copy/VAD.se674
VAD.se674,1,copy : package/lib/lib/videnc_copy_dma/VAD.se674
.PHONY: Filter.oe674,copy
Filter.oe674,copy : Filter.oe674,0,copy Filter.oe674,1,copy 
	@

Filter.oe674,0,copy : package/lib/lib/videnc_copy/Filter.oe674
Filter.oe674,1,copy : package/lib/lib/videnc_copy_dma/Filter.oe674
.PHONY: Filter.se674,copy
Filter.se674,copy : Filter.se674,0,copy Filter.se674,1,copy 
	@

Filter.se674,0,copy : package/lib/lib/videnc_copy/Filter.se674
Filter.se674,1,copy : package/lib/lib/videnc_copy_dma/Filter.se674
.PHONY: CalcGaussLh.oe674,copy
CalcGaussLh.oe674,copy : CalcGaussLh.oe674,0,copy CalcGaussLh.oe674,1,copy 
	@

CalcGaussLh.oe674,0,copy : package/lib/lib/videnc_copy/CalcGaussLh.oe674
CalcGaussLh.oe674,1,copy : package/lib/lib/videnc_copy_dma/CalcGaussLh.oe674
.PHONY: CalcGaussLh.se674,copy
CalcGaussLh.se674,copy : CalcGaussLh.se674,0,copy CalcGaussLh.se674,1,copy 
	@

CalcGaussLh.se674,0,copy : package/lib/lib/videnc_copy/CalcGaussLh.se674
CalcGaussLh.se674,1,copy : package/lib/lib/videnc_copy_dma/CalcGaussLh.se674
.PHONY: DSPCFFT.oe674,copy
DSPCFFT.oe674,copy : DSPCFFT.oe674,0,copy DSPCFFT.oe674,1,copy 
	@

DSPCFFT.oe674,0,copy : package/lib/lib/videnc_copy/DSPCFFT.oe674
DSPCFFT.oe674,1,copy : package/lib/lib/videnc_copy_dma/DSPCFFT.oe674
.PHONY: DSPCFFT.se674,copy
DSPCFFT.se674,copy : DSPCFFT.se674,0,copy DSPCFFT.se674,1,copy 
	@

DSPCFFT.se674,0,copy : package/lib/lib/videnc_copy/DSPCFFT.se674
DSPCFFT.se674,1,copy : package/lib/lib/videnc_copy_dma/DSPCFFT.se674
.PHONY: DspWordDict.oe674,copy
DspWordDict.oe674,copy : DspWordDict.oe674,0,copy DspWordDict.oe674,1,copy 
	@

DspWordDict.oe674,0,copy : package/lib/lib/videnc_copy/DspWordDict.oe674
DspWordDict.oe674,1,copy : package/lib/lib/videnc_copy_dma/DspWordDict.oe674
.PHONY: DspWordDict.se674,copy
DspWordDict.se674,copy : DspWordDict.se674,0,copy DspWordDict.se674,1,copy 
	@

DspWordDict.se674,0,copy : package/lib/lib/videnc_copy/DspWordDict.se674
DspWordDict.se674,1,copy : package/lib/lib/videnc_copy_dma/DspWordDict.se674
.PHONY: DSPCmdWordRecg.oe674,copy
DSPCmdWordRecg.oe674,copy : DSPCmdWordRecg.oe674,0,copy DSPCmdWordRecg.oe674,1,copy 
	@

DSPCmdWordRecg.oe674,0,copy : package/lib/lib/videnc_copy/DSPCmdWordRecg.oe674
DSPCmdWordRecg.oe674,1,copy : package/lib/lib/videnc_copy_dma/DSPCmdWordRecg.oe674
.PHONY: DSPCmdWordRecg.se674,copy
DSPCmdWordRecg.se674,copy : DSPCmdWordRecg.se674,0,copy DSPCmdWordRecg.se674,1,copy 
	@

DSPCmdWordRecg.se674,0,copy : package/lib/lib/videnc_copy/DSPCmdWordRecg.se674
DSPCmdWordRecg.se674,1,copy : package/lib/lib/videnc_copy_dma/DSPCmdWordRecg.se674
.PHONY: DspCodeBooks.oe674,copy
DspCodeBooks.oe674,copy : DspCodeBooks.oe674,0,copy DspCodeBooks.oe674,1,copy 
	@

DspCodeBooks.oe674,0,copy : package/lib/lib/videnc_copy/DspCodeBooks.oe674
DspCodeBooks.oe674,1,copy : package/lib/lib/videnc_copy_dma/DspCodeBooks.oe674
.PHONY: DspCodeBooks.se674,copy
DspCodeBooks.se674,copy : DspCodeBooks.se674,0,copy DspCodeBooks.se674,1,copy 
	@

DspCodeBooks.se674,0,copy : package/lib/lib/videnc_copy/DspCodeBooks.se674
DspCodeBooks.se674,1,copy : package/lib/lib/videnc_copy_dma/DspCodeBooks.se674
.PHONY: DspGMMCalc.oe674,copy
DspGMMCalc.oe674,copy : DspGMMCalc.oe674,0,copy DspGMMCalc.oe674,1,copy 
	@

DspGMMCalc.oe674,0,copy : package/lib/lib/videnc_copy/DspGMMCalc.oe674
DspGMMCalc.oe674,1,copy : package/lib/lib/videnc_copy_dma/DspGMMCalc.oe674
.PHONY: DspGMMCalc.se674,copy
DspGMMCalc.se674,copy : DspGMMCalc.se674,0,copy DspGMMCalc.se674,1,copy 
	@

DspGMMCalc.se674,0,copy : package/lib/lib/videnc_copy/DspGMMCalc.se674
DspGMMCalc.se674,1,copy : package/lib/lib/videnc_copy_dma/DspGMMCalc.se674
.PHONY: DSPMFCC.oe674,copy
DSPMFCC.oe674,copy : DSPMFCC.oe674,0,copy DSPMFCC.oe674,1,copy 
	@

DSPMFCC.oe674,0,copy : package/lib/lib/videnc_copy/DSPMFCC.oe674
DSPMFCC.oe674,1,copy : package/lib/lib/videnc_copy_dma/DSPMFCC.oe674
.PHONY: DSPMFCC.se674,copy
DSPMFCC.se674,copy : DSPMFCC.se674,0,copy DSPMFCC.se674,1,copy 
	@

DSPMFCC.se674,0,copy : package/lib/lib/videnc_copy/DSPMFCC.se674
DSPMFCC.se674,1,copy : package/lib/lib/videnc_copy_dma/DSPMFCC.se674
.PHONY: DSPSegmentAlgorithm.oe674,copy
DSPSegmentAlgorithm.oe674,copy : DSPSegmentAlgorithm.oe674,0,copy DSPSegmentAlgorithm.oe674,1,copy 
	@

DSPSegmentAlgorithm.oe674,0,copy : package/lib/lib/videnc_copy/DSPSegmentAlgorithm.oe674
DSPSegmentAlgorithm.oe674,1,copy : package/lib/lib/videnc_copy_dma/DSPSegmentAlgorithm.oe674
.PHONY: DSPSegmentAlgorithm.se674,copy
DSPSegmentAlgorithm.se674,copy : DSPSegmentAlgorithm.se674,0,copy DSPSegmentAlgorithm.se674,1,copy 
	@

DSPSegmentAlgorithm.se674,0,copy : package/lib/lib/videnc_copy/DSPSegmentAlgorithm.se674
DSPSegmentAlgorithm.se674,1,copy : package/lib/lib/videnc_copy_dma/DSPSegmentAlgorithm.se674
.PHONY: DSPStateTrace.oe674,copy
DSPStateTrace.oe674,copy : DSPStateTrace.oe674,0,copy DSPStateTrace.oe674,1,copy 
	@

DSPStateTrace.oe674,0,copy : package/lib/lib/videnc_copy/DSPStateTrace.oe674
DSPStateTrace.oe674,1,copy : package/lib/lib/videnc_copy_dma/DSPStateTrace.oe674
.PHONY: DSPStateTrace.se674,copy
DSPStateTrace.se674,copy : DSPStateTrace.se674,0,copy DSPStateTrace.se674,1,copy 
	@

DSPStateTrace.se674,0,copy : package/lib/lib/videnc_copy/DSPStateTrace.se674
DSPStateTrace.se674,1,copy : package/lib/lib/videnc_copy_dma/DSPStateTrace.se674
.PHONY: DSPStateTraceBin.oe674,copy
DSPStateTraceBin.oe674,copy : DSPStateTraceBin.oe674,0,copy DSPStateTraceBin.oe674,1,copy 
	@

DSPStateTraceBin.oe674,0,copy : package/lib/lib/videnc_copy/DSPStateTraceBin.oe674
DSPStateTraceBin.oe674,1,copy : package/lib/lib/videnc_copy_dma/DSPStateTraceBin.oe674
.PHONY: DSPStateTraceBin.se674,copy
DSPStateTraceBin.se674,copy : DSPStateTraceBin.se674,0,copy DSPStateTraceBin.se674,1,copy 
	@

DSPStateTraceBin.se674,0,copy : package/lib/lib/videnc_copy/DSPStateTraceBin.se674
DSPStateTraceBin.se674,1,copy : package/lib/lib/videnc_copy_dma/DSPStateTraceBin.se674
package_ti.sdo.ce.examples.codecs.videnc_copy.ov5T,copy : package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.ov5T
package_ti.sdo.ce.examples.codecs.videnc_copy.sv5T,copy : package/lib/lib/videnc_copy/package/package_ti.sdo.ce.examples.codecs.videnc_copy.sv5T
videnc_copy.ov5T,copy : package/lib/lib/videnc_copy/videnc_copy.ov5T
videnc_copy.sv5T,copy : package/lib/lib/videnc_copy/videnc_copy.sv5T
VAD.ov5T,copy : package/lib/lib/videnc_copy/VAD.ov5T
VAD.sv5T,copy : package/lib/lib/videnc_copy/VAD.sv5T
Filter.ov5T,copy : package/lib/lib/videnc_copy/Filter.ov5T
Filter.sv5T,copy : package/lib/lib/videnc_copy/Filter.sv5T
CalcGaussLh.ov5T,copy : package/lib/lib/videnc_copy/CalcGaussLh.ov5T
CalcGaussLh.sv5T,copy : package/lib/lib/videnc_copy/CalcGaussLh.sv5T
DSPCFFT.ov5T,copy : package/lib/lib/videnc_copy/DSPCFFT.ov5T
DSPCFFT.sv5T,copy : package/lib/lib/videnc_copy/DSPCFFT.sv5T
DspWordDict.ov5T,copy : package/lib/lib/videnc_copy/DspWordDict.ov5T
DspWordDict.sv5T,copy : package/lib/lib/videnc_copy/DspWordDict.sv5T
DSPCmdWordRecg.ov5T,copy : package/lib/lib/videnc_copy/DSPCmdWordRecg.ov5T
DSPCmdWordRecg.sv5T,copy : package/lib/lib/videnc_copy/DSPCmdWordRecg.sv5T
DspCodeBooks.ov5T,copy : package/lib/lib/videnc_copy/DspCodeBooks.ov5T
DspCodeBooks.sv5T,copy : package/lib/lib/videnc_copy/DspCodeBooks.sv5T
DspGMMCalc.ov5T,copy : package/lib/lib/videnc_copy/DspGMMCalc.ov5T
DspGMMCalc.sv5T,copy : package/lib/lib/videnc_copy/DspGMMCalc.sv5T
DSPMFCC.ov5T,copy : package/lib/lib/videnc_copy/DSPMFCC.ov5T
DSPMFCC.sv5T,copy : package/lib/lib/videnc_copy/DSPMFCC.sv5T
DSPSegmentAlgorithm.ov5T,copy : package/lib/lib/videnc_copy/DSPSegmentAlgorithm.ov5T
DSPSegmentAlgorithm.sv5T,copy : package/lib/lib/videnc_copy/DSPSegmentAlgorithm.sv5T
DSPStateTrace.ov5T,copy : package/lib/lib/videnc_copy/DSPStateTrace.ov5T
DSPStateTrace.sv5T,copy : package/lib/lib/videnc_copy/DSPStateTrace.sv5T
DSPStateTraceBin.ov5T,copy : package/lib/lib/videnc_copy/DSPStateTraceBin.ov5T
DSPStateTraceBin.sv5T,copy : package/lib/lib/videnc_copy/DSPStateTraceBin.sv5T

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ce_examples_codecs_videnc_copy
ti_sdo_ce_examples_codecs_videnc_copy.tar: package/package.bld.xml
ti_sdo_ce_examples_codecs_videnc_copy.tar: package/package.ext.xml
ti_sdo_ce_examples_codecs_videnc_copy.tar: package/package.rel.dot
ti_sdo_ce_examples_codecs_videnc_copy.tar: package/build.cfg
ti_sdo_ce_examples_codecs_videnc_copy.tar: package/package.xdc.inc
ti_sdo_ce_examples_codecs_videnc_copy.tar: package/package.cfg.xdc.inc
ti_sdo_ce_examples_codecs_videnc_copy.tar: lib/videnc_copy_dma.ae674
ti_sdo_ce_examples_codecs_videnc_copy.tar: lib/videnc_copy.ae674
ti_sdo_ce_examples_codecs_videnc_copy.tar: lib/videnc_copy.av5T
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_sdo_ce_examples_codecs_videnc_copy.tar.dep
endif
package/rel/ti_sdo_ce_examples_codecs_videnc_copy/ti/sdo/ce/examples/codecs/videnc_copy/package/package.rel.xml:

ti_sdo_ce_examples_codecs_videnc_copy.tar: package/rel/ti_sdo_ce_examples_codecs_videnc_copy.xdc.inc package/rel/ti_sdo_ce_examples_codecs_videnc_copy/ti/sdo/ce/examples/codecs/videnc_copy/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_ce_examples_codecs_videnc_copy.xdc.inc,package/rel/ti_sdo_ce_examples_codecs_videnc_copy.tar.dep)


release release,ti_sdo_ce_examples_codecs_videnc_copy: all ti_sdo_ce_examples_codecs_videnc_copy.tar
clean:: .clean
	-$(RM) ti_sdo_ce_examples_codecs_videnc_copy.tar
	-$(RM) package/rel/ti_sdo_ce_examples_codecs_videnc_copy.xdc.inc
	-$(RM) package/rel/ti_sdo_ce_examples_codecs_videnc_copy.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/videnc_copy_dma))
    $(shell $(MKDIR) package/lib/lib/videnc_copy_dma)
endif
ifeq (,$(wildcard package/lib/lib/videnc_copy_dma/package))
    $(shell $(MKDIR) package/lib/lib/videnc_copy_dma/package)
endif
ifeq (,$(wildcard package/lib/lib/videnc_copy))
    $(shell $(MKDIR) package/lib/lib/videnc_copy)
endif
ifeq (,$(wildcard package/lib/lib/videnc_copy/package))
    $(shell $(MKDIR) package/lib/lib/videnc_copy/package)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.sdo.ce.examples.codecs.videnc_copy.pjt
